// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/kujilabo/cocotola-api/src/app/domain"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ProblemSelectParameter1 is an autogenerated mock type for the ProblemSelectParameter1 type
type ProblemSelectParameter1 struct {
	mock.Mock
}

// GetProblemID provides a mock function with given fields:
func (_m *ProblemSelectParameter1) GetProblemID() domain.ProblemID {
	ret := _m.Called()

	var r0 domain.ProblemID
	if rf, ok := ret.Get(0).(func() domain.ProblemID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.ProblemID)
	}

	return r0
}

// GetWorkbookID provides a mock function with given fields:
func (_m *ProblemSelectParameter1) GetWorkbookID() domain.WorkbookID {
	ret := _m.Called()

	var r0 domain.WorkbookID
	if rf, ok := ret.Get(0).(func() domain.WorkbookID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.WorkbookID)
	}

	return r0
}

// NewProblemSelectParameter1 creates a new instance of ProblemSelectParameter1. It also registers a cleanup function to assert the mocks expectations.
func NewProblemSelectParameter1(t testing.TB) *ProblemSelectParameter1 {
	mock := &ProblemSelectParameter1{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
