// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// WorkbookUpdateParameter is an autogenerated mock type for the WorkbookUpdateParameter type
type WorkbookUpdateParameter struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *WorkbookUpdateParameter) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetQuestionText provides a mock function with given fields:
func (_m *WorkbookUpdateParameter) GetQuestionText() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewWorkbookUpdateParameter creates a new instance of WorkbookUpdateParameter. It also registers a cleanup function to assert the mocks expectations.
func NewWorkbookUpdateParameter(t testing.TB) *WorkbookUpdateParameter {
	mock := &WorkbookUpdateParameter{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
