// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// StudyType is an autogenerated mock type for the StudyType type
type StudyType struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *StudyType) GetID() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *StudyType) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewStudyType creates a new instance of StudyType. It also registers a cleanup function to assert the mocks expectations.
func NewStudyType(t testing.TB) *StudyType {
	mock := &StudyType{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
