// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	service "github.com/kujilabo/cocotola-api/pkg_app/service"
	mock "github.com/stretchr/testify/mock"
)

// ProcessorFactory is an autogenerated mock type for the ProcessorFactory type
type ProcessorFactory struct {
	mock.Mock
}

// NewProblemAddProcessor provides a mock function with given fields: processorType
func (_m *ProcessorFactory) NewProblemAddProcessor(processorType string) (service.ProblemAddProcessor, error) {
	ret := _m.Called(processorType)

	var r0 service.ProblemAddProcessor
	if rf, ok := ret.Get(0).(func(string) service.ProblemAddProcessor); ok {
		r0 = rf(processorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ProblemAddProcessor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(processorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProblemImportProcessor provides a mock function with given fields: processorType
func (_m *ProcessorFactory) NewProblemImportProcessor(processorType string) (service.ProblemImportProcessor, error) {
	ret := _m.Called(processorType)

	var r0 service.ProblemImportProcessor
	if rf, ok := ret.Get(0).(func(string) service.ProblemImportProcessor); ok {
		r0 = rf(processorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ProblemImportProcessor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(processorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProblemQuotaProcessor provides a mock function with given fields: processorType
func (_m *ProcessorFactory) NewProblemQuotaProcessor(processorType string) (service.ProblemQuotaProcessor, error) {
	ret := _m.Called(processorType)

	var r0 service.ProblemQuotaProcessor
	if rf, ok := ret.Get(0).(func(string) service.ProblemQuotaProcessor); ok {
		r0 = rf(processorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ProblemQuotaProcessor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(processorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProblemRemoveProcessor provides a mock function with given fields: processorType
func (_m *ProcessorFactory) NewProblemRemoveProcessor(processorType string) (service.ProblemRemoveProcessor, error) {
	ret := _m.Called(processorType)

	var r0 service.ProblemRemoveProcessor
	if rf, ok := ret.Get(0).(func(string) service.ProblemRemoveProcessor); ok {
		r0 = rf(processorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ProblemRemoveProcessor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(processorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProblemUpdateProcessor provides a mock function with given fields: processorType
func (_m *ProcessorFactory) NewProblemUpdateProcessor(processorType string) (service.ProblemUpdateProcessor, error) {
	ret := _m.Called(processorType)

	var r0 service.ProblemUpdateProcessor
	if rf, ok := ret.Get(0).(func(string) service.ProblemUpdateProcessor); ok {
		r0 = rf(processorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ProblemUpdateProcessor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(processorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProcessorFactory creates a new instance of ProcessorFactory. It also registers a cleanup function to assert the mocks expectations.
func NewProcessorFactory(t testing.TB) *ProcessorFactory {
	mock := &ProcessorFactory{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
