// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kujilabo/cocotola-api/pkg_app/domain"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Synthesizer is an autogenerated mock type for the Synthesizer type
type Synthesizer struct {
	mock.Mock
}

// Synthesize provides a mock function with given fields: ctx, lang, text
func (_m *Synthesizer) Synthesize(ctx context.Context, lang domain.Lang5, text string) (string, error) {
	ret := _m.Called(ctx, lang, text)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang5, string) string); ok {
		r0 = rf(ctx, lang, text)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang5, string) error); ok {
		r1 = rf(ctx, lang, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSynthesizer creates a new instance of Synthesizer. It also registers a cleanup function to assert the mocks expectations.
func NewSynthesizer(t testing.TB) *Synthesizer {
	mock := &Synthesizer{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
