// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	commondomain "github.com/kujilabo/cocotola-api/pkg_plugin/common/domain"

	domain "github.com/kujilabo/cocotola-api/pkg_app/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/kujilabo/cocotola-api/pkg_plugin/common/service"

	testing "testing"
)

// TranslationClient is an autogenerated mock type for the TranslationClient type
type TranslationClient struct {
	mock.Mock
}

// AddTranslation provides a mock function with given fields: ctx, param
func (_m *TranslationClient) AddTranslation(ctx context.Context, param service.TranslationAddParameter) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TranslationAddParameter) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DictionaryLookup provides a mock function with given fields: ctx, fromLang, toLang, text
func (_m *TranslationClient) DictionaryLookup(ctx context.Context, fromLang domain.Lang2, toLang domain.Lang2, text string) ([]commondomain.Translation, error) {
	ret := _m.Called(ctx, fromLang, toLang, text)

	var r0 []commondomain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, domain.Lang2, string) []commondomain.Translation); ok {
		r0 = rf(ctx, fromLang, toLang, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]commondomain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, domain.Lang2, string) error); ok {
		r1 = rf(ctx, fromLang, toLang, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DictionaryLookupWithPos provides a mock function with given fields: ctx, fromLang, toLang, text, pos
func (_m *TranslationClient) DictionaryLookupWithPos(ctx context.Context, fromLang domain.Lang2, toLang domain.Lang2, text string, pos commondomain.WordPos) (commondomain.Translation, error) {
	ret := _m.Called(ctx, fromLang, toLang, text, pos)

	var r0 commondomain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, domain.Lang2, string, commondomain.WordPos) commondomain.Translation); ok {
		r0 = rf(ctx, fromLang, toLang, text, pos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(commondomain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, domain.Lang2, string, commondomain.WordPos) error); ok {
		r1 = rf(ctx, fromLang, toLang, text, pos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTranslationByTextAndPos provides a mock function with given fields: ctx, lang, text, pos
func (_m *TranslationClient) FindTranslationByTextAndPos(ctx context.Context, lang domain.Lang2, text string, pos commondomain.WordPos) (commondomain.Translation, error) {
	ret := _m.Called(ctx, lang, text, pos)

	var r0 commondomain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, commondomain.WordPos) commondomain.Translation); ok {
		r0 = rf(ctx, lang, text, pos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(commondomain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string, commondomain.WordPos) error); ok {
		r1 = rf(ctx, lang, text, pos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTranslationsByFirstLetter provides a mock function with given fields: ctx, lang, firstLetter
func (_m *TranslationClient) FindTranslationsByFirstLetter(ctx context.Context, lang domain.Lang2, firstLetter string) ([]commondomain.Translation, error) {
	ret := _m.Called(ctx, lang, firstLetter)

	var r0 []commondomain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string) []commondomain.Translation); ok {
		r0 = rf(ctx, lang, firstLetter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]commondomain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string) error); ok {
		r1 = rf(ctx, lang, firstLetter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTranslationsByText provides a mock function with given fields: ctx, lang, text
func (_m *TranslationClient) FindTranslationsByText(ctx context.Context, lang domain.Lang2, text string) ([]commondomain.Translation, error) {
	ret := _m.Called(ctx, lang, text)

	var r0 []commondomain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string) []commondomain.Translation); ok {
		r0 = rf(ctx, lang, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]commondomain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string) error); ok {
		r1 = rf(ctx, lang, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveTranslation provides a mock function with given fields: ctx, lang, text, pos
func (_m *TranslationClient) RemoveTranslation(ctx context.Context, lang domain.Lang2, text string, pos commondomain.WordPos) error {
	ret := _m.Called(ctx, lang, text, pos)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, commondomain.WordPos) error); ok {
		r0 = rf(ctx, lang, text, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTranslation provides a mock function with given fields: ctx, lang, text, pos, param
func (_m *TranslationClient) UpdateTranslation(ctx context.Context, lang domain.Lang2, text string, pos commondomain.WordPos, param service.TranslationUpdateParameter) error {
	ret := _m.Called(ctx, lang, text, pos, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, commondomain.WordPos, service.TranslationUpdateParameter) error); ok {
		r0 = rf(ctx, lang, text, pos, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTranslationClient creates a new instance of TranslationClient. It also registers a cleanup function to assert the mocks expectations.
func NewTranslationClient(t testing.TB) *TranslationClient {
	mock := &TranslationClient{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
