---
app:
  ownerPassword: password
auth:
  signingKey: ah5T9Y9V2JPU74fhCtHQfDqLp3Zg8ZNc
  accessTokenTtlMin: 5
  refreshTokenTtlHour: 720
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
debug:
  ginMode: true
  wait: true
