---
app:
  name: cocotola-api
  httpPort: 8080
  ownerPassword: password
  testUserEmail: $TEST_USER_EMAIL
db:
  # driverName: sqlite3
  # sqlite3:
  #   file: app.db
  driverName: mysql
  mysql:
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: development
auth:
  signingKey: ah5T9Y9V2JPU74fhCtHQfDqLp3Zg8ZNc
  accessTokenTtlMin: 5
  refreshTokenTtlHour: 720
  googleCallbackUrl: http://localhost:3000/app/callback
  googleClientId: 830416463276-3ts1rsinahi0hdnsfc10m6mabpttrd5i.apps.googleusercontent.com
  googleClientSecret: $GOOGLE_CLIENT_SECRET
  apiTimeoutSec: 5
translator:
  endpoint: http://localhost:8180
  timeoutSec: 3
  username: user
  password: password
  grpcAddr: localhost:50151
trace:
  exporter: jaeger
  jaeger:
    endpoint: http://localhost:14268/api/traces
tatoeba:
  endpoint: http://localhost:8280
  timeoutSec: 3
  username: user
  password: password
synthesizer:
  endpoint: http://localhost:8380
  timeoutSec: 3
  username: user
  password: password
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
swagger:
  enabled: true
  host: localhost:8080
  schema: http
debug:
  ginMode: true
  # wait: true
