---
app:
  ownerPassword: $OWNER_PASSWORD
auth:
  signingKey: $SIGNING_KEY
  accessTokenTtlMin: 5
  refreshTokenTtlHour: 720
cors:
  allowOrigins:
    - "https://www.cocotola.com"
shutdown:
  timeSec1: 1
  timeSec2: 1
debug:
  ginMode: false
  wait: false
