---
app:
  ownerPassword: $OWNER_PASSWORD
  testUserEmail: $TEST_USER_EMAIL
db:
  driverName: mysql
  mysql:
    username: $MYSQL_USERNAME
    password: $MYSQL_PASSWORD
    host: $MYSQL_HOST
    port: $MYSQL_PORT
    database: $MYSQL_DATABASE
auth:
  signingKey: $SIGNING_KEY
  accessTokenTtlMin: 5
  refreshTokenTtlHour: 720
  googleCallbackUrl: https://www.cocotola.com/app/callback
  googleClientId: 830416463276-lf7d9r39v1ct78u6p1dke6cv5kd8g6o1.apps.googleusercontent.com
  googleClientSecret: $GOOGLE_CLIENT_SECRET
google:
  synthesizerKey: $SYNTHESIZER_KEY
  synthesizerTimeoutSec: 10
azure:
  subscriptionKey: $SUBSCRIPTION_KEY
cors:
  allowOrigins:
    - "https://www.cocotola.com"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
debug:
  ginMode: false
  wait: false
