// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/private/workbook": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Create new workbook",
                "parameters": [
                    {
                        "description": "parameter to create new workbook",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookAddParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlerhelper.IDResponse"
                        }
                    },
                    "400": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/private/workbook/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Find workbooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookSearchResponse"
                        }
                    },
                    "400": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/private/workbook/{workbookID}": {
            "put": {
                "description": "update the workbook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update the workbook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workbook ID",
                        "name": "workbookID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "parameter to update the workbook",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookUpdateParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlerhelper.IDResponse"
                        }
                    },
                    "400": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/study/workbook/{workbookID}/study_type/{studyType}": {
            "get": {
                "description": "find results of workbook",
                "produces": [
                    "application/json"
                ],
                "summary": "Find the recordbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workbook ID",
                        "name": "workbookID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Study type",
                        "name": "studyType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ProblemWithLevelList"
                        }
                    },
                    "400": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ProblemWithLevel": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "problemId": {
                    "type": "integer"
                }
            }
        },
        "entity.ProblemWithLevelList": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ProblemWithLevel"
                    }
                }
            }
        },
        "entity.Workbook": {
            "type": "object",
            "required": [
                "createdBy",
                "id",
                "updatedBy",
                "version"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer",
                    "minimum": 1
                },
                "id": {
                    "type": "integer",
                    "minimum": 1
                },
                "name": {
                    "type": "string"
                },
                "problemType": {
                    "type": "string"
                },
                "questionText": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer",
                    "minimum": 1
                },
                "version": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "entity.WorkbookAddParameter": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "problemType": {
                    "type": "string",
                    "enum": [
                        "english_word",
                        "english_phrase",
                        "english_sentence",
                        "template"
                    ]
                },
                "questionText": {
                    "type": "string"
                }
            }
        },
        "entity.WorkbookSearchResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Workbook"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "entity.WorkbookUpdateParameter": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "questionText": {
                    "type": "string"
                }
            }
        },
        "handlerhelper.IDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
