// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	userdomain "github.com/kujilabo/cocotola-api/src/user/domain"
)

// SystemStudentModel is an autogenerated mock type for the SystemStudentModel type
type SystemStudentModel struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *SystemStudentModel) GetID() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// GetLoginID provides a mock function with given fields:
func (_m *SystemStudentModel) GetLoginID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOrganizationID provides a mock function with given fields:
func (_m *SystemStudentModel) GetOrganizationID() userdomain.OrganizationID {
	ret := _m.Called()

	var r0 userdomain.OrganizationID
	if rf, ok := ret.Get(0).(func() userdomain.OrganizationID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(userdomain.OrganizationID)
	}

	return r0
}

// GetProperties provides a mock function with given fields:
func (_m *SystemStudentModel) GetProperties() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetRoles provides a mock function with given fields:
func (_m *SystemStudentModel) GetRoles() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetUsername provides a mock function with given fields:
func (_m *SystemStudentModel) GetUsername() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewSystemStudentModel creates a new instance of SystemStudentModel. It also registers a cleanup function to assert the mocks expectations.
func NewSystemStudentModel(t testing.TB) *SystemStudentModel {
	mock := &SystemStudentModel{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
