---
on: [pull_request]
name: Reviewdog
jobs:
  staticcheck:
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Report all results.
          filter_mode: nofilter
          # Exit with 1 when it find at least one finding.
          fail_on_error: true

  # NOTE: golangci-lint doesn't report multiple errors on the same line from
  # different linters and just report one of the errors?

  # Use golint via golangci-lint binary with "warning" level.
  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E golint"
          tool_name: golint
          level: warning

  # You can add more and more supported linters with different config.
  errcheck:
    name: runner / errcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: errcheck
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E errcheck"
          tool_name: errcheck
          level: info

  gosec:
    name: runner / gosec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: gosec
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E gosec"
          tool_name: gosec

  gocyclo:
    name: runner / gocyclo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: gocyclo
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E gocyclo"
          tool_name: gocyclo
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          locale: "US"

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
